# path to a directory with all packages
storage: ../../tmp/local-registry/storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    maxage: 30m
    fail_timeout: 10m
    timeout: 600s
    agent_options:
      keepAlive: true
      maxSockets: 40
      maxFreeSockets: 10
    cache: false

packages:
  '@nrwl/*':
    access: $all
    publish: $all

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

# log settings
logs:
  - { type: stdout, format: pretty, level: warn }
