matrix:
  include:
    - os: linux
      language: node_js
      node_js: 10
      dist: trusty
      sudo: required
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn checkformat --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'
        - yarn checkcommit
        - yarn checkimports
        - yarn documentation
        - yarn test:all
    - os: linux
      language: node_js
      node_js: 10
      dist: trusty
      sudo: required
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn checkformat --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'
        - yarn e2e

notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true
