version: 2.1

# Variables
var_1: &working_directory ~/repo

executors:
  linux:
    working_directory: *working_directory
    docker:
      - image: cimg/node:12.20-browsers

  windows:
    working_directory: *working_directory
    resource_class: windows.medium
    machine:
      image: windows-server-2019-vs2019:stable
    shell: cmd.exe

commands:
  setup:
    parameters:
      os:
        type: string
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - nrwl-nx-yarn-packages-<< parameters.os >>-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          # Windows needs its own cache key because binaries in node_modules are different.
          key: nrwl-nx-yarn-packages-<< parameters.os >>-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  checks-and-unit-tests:
    parameters:
      os:
        type: string
        default: 'linux'
    executor: << parameters.os >>
    steps:
      - setup:
          os: << parameters.os >>
      - run:
          name: Check Documentation
          command: yarn documentation
      - run:
          name: Check Imports
          command: yarn check-imports
      - run:
          name: Check Formatting
          command: yarn check-format
      - run:
          name: Run linting
          command: yarn lint
      - run:
          name: Check Commit Message Format
          command: yarn check-commit
      - run:
          name: Check Package dependencies
          command: yarn depcheck
  e2e:
    parameters:
      os:
        type: string
      packages:
        type: string
      cli:
        type: string
        default: ''
    executor: << parameters.os >>
    steps:
      - setup:
          os: << parameters.os >>
      - run:
          name: Run E2E tests - << parameters.packages >>
          command: yarn e2e << parameters.packages >> affected
          no_output_timeout: 30m
    environment:
      SELECTED_CLI: << parameters.cli >>

workflows:
  build:
    jobs:
      - checks-and-unit-tests
      - e2e:
          matrix:
            parameters:
              os: ['linux', 'windows']
              packages:
                [
                  'e2e-workspace',
                  'e2e-cli,e2e-nx-plugin,dep-graph-client-e2e',
                  'e2e-cypress,e2e-jest',
                  'e2e-react',
                  'e2e-next',
                  'e2e-node',
                  'e2e-web,e2e-linter,e2e-storybook',
                ]
      - e2e:
          matrix:
            parameters:
              os: ['linux', 'windows']
              packages: ['e2e-angular']
          cli: 'angular'
