name: E2E matrix

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
        node_version:
          - 14.x
          # - 15.x
        package_manager:
          - npm
          - yarn
          - pnpm
        packages:
          - e2e-workspace
          - e2e-cli,e2e-nx-plugin,dep-graph-dep-graph-e2e
          - e2e-cypress,e2e-jest
          - e2e-react
          - e2e-next
          - e2e-gatsby
          - e2e-node
          - e2e-web,e2e-linter,e2e-storybook
          - e2e-angular
      fail-fast: false

    name: Node v${{ matrix.node_version }} (${{ matrix.package_manager }}) - ${{ matrix.packages }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - run: yarn install

    - name: Cleanup
      run: |
        # Workaround to provide additional free space for testing.
        # https://github.com/actions/virtual-environments/issues/2840
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install PNPM
      if: ${{ matrix.package_manager == 'pnpm' }}
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2

    - name: Run e2e tests
      run: yarn nx run-many --target=e2e --projects=${{ matrix.packages }}
      env:
        GIT_AUTHOR_NAME: test@test.com
        GIT_AUTHOR_EMAIL: Test
        GIT_COMMITTER_EMAIL: test@test.com
        GIT_COMMITTER_NAME: Test
        NX_E2E_CI_CACHE_KEY: e2e-gha-${{ matrix.node_version }}-${{ matrix.package_manager }}
        NODE_OPTIONS: --max_old_space_size=8192
        SELECTED_PM: ${{ matrix.package_manager }}
        SELECTED_CLI: ${{ matrix.packages == 'e2e-angular' && 'angular' || 'nx' }}
